language: java
jdk: openjdk8

env:
  global:
  - REPO=adaptrislabs/interlok-hello-world
  - HEROKU_APP=interlok-hello-world
  - HEROKU_URL=https://interlok-hello-world.herokuapp.com/

services:
  - docker

install:
  - ./gradlew check docker

script:
  - docker run -it --rm -e INTERLOK_OPTS="-configtest bootstrap.properties" -e PORT=8080 $REPO:latest
 
after_success:
 - ./deploy.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
