language: java

env:
  global:
  - REPO=mcwarman/interlok-hello-world

services:
  - docker

install:
  - docker build -t $REPO:$TRAVIS_BUILD_NUMBER .

script:
  - docker run -it --rm -e INTERLOK_OPTS="-configtest bootstrap.properties" $REPO:$TRAVIS_BUILD_NUMBER
  - gradle check

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
