name: dependabot-publisher
on:
  workflow_run:
    workflows: ["is-dependabot"]
    types:
      - completed

# https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable-publish.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      HEROKU_KEY: ${{ secrets.HEROKU_KEY }}
