name: Interlok CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 11.0
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - name: Gradle Wrapper Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
    - name: Gradle Dependencies Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
    - name: Gradle Check & Docker
      run: |
        ./gradlew -Dorg.gradle.console=plain --no-daemon -PverboseTests=true check sonarqube docker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Docker Image Check
      run: |
        docker run -it --rm -e INTERLOK_OPTS="-configtest bootstrap.properties" -e PORT=8080 adaptrislabs/interlok-hello-world:latest