name: Publish

on:
  push:
    branches:
      - master

jobs:
  main:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/reusable-publish.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      HEROKU_KEY: ${{ secrets.HEROKU_KEY }}
